Add compatibility for internal QE test automation
redhat-nfvpe/container-perf-tools pull request #22
Opened 2024-04-11 18:45 UTC by dgonyier

Required to preserve backwards compatibility with internal automation that utilizes stress-ng pods while preserving functionality of the other environment variable managed settings.

2024-04-11 22:39 UTC, bartwensley requested changes
Looks good - just a couple minor comments.

2024-04-11 22:39 UTC, bartwensley commented on stress-ng/cmd.sh
> +if [ "${CMDLINE}" == "" ]; then
Please change to the following to be consistent with the other tests in this script:
`if [[ -z "${CMDLINE}" ]]; then`

2024-04-11 22:39 UTC, bartwensley commented on stress-ng/cmd.sh
> +    trap sigfunc TERM INT SIGUSR1
This is a behaviour change as trap was also done in the manual case as well - can you do it before the if statement?

2024-04-12 02:08 UTC, dgonyier commented
@bartwensley I addressed your comments. Please take a look.

2024-04-12 14:35 UTC, bartwensley approved these changes
Looks good.

2024-04-12 14:37 UTC, merged